version: "3.8"

services:
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile.network
    container_name: aeth-bootnode
    command: ["--role", "full", "--port", "4001", "--stake", "1000000", "--metrics-port", "8080"]
    ports:
      - "4001:4001"
      - "8080:8080"
    networks:
      - aeth-mesh

  sequencer-primary:
    build:
      context: .
      dockerfile: Dockerfile.network
    container_name: aeth-sequencer-primary
    depends_on:
      - bootnode
    command: ["--role", "sequencer", "--bootnodes", "/ip4/172.18.0.5/tcp/4001/p2p/12D3KooWJUg5Sq3d1CqY6ofkhav3mLvq79R1jqcoDW5ALyn3U2qb", "--stake", "5000000", "--metrics-port", "8080"]
    networks:
      - aeth-mesh

  prover-01:
    build:
      context: .
      dockerfile: Dockerfile.prover
    container_name: aeth-prover-01
    depends_on:
      - sequencer-primary
    command: ["--metrics-port", "8083"]
    networks:
      - aeth-mesh

  prometheus:
    image: prom/prometheus:latest
    container_name: aeth-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9091:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - aeth-mesh

  grafana:
    image: grafana/grafana:latest
    container_name: aeth-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=aetheris
    networks:
      - aeth-mesh

  trading-defense:
    build:
      context: /Users/jpb/Downloads/
      dockerfile: /Users/jpb/Downloads/aeth-protocol/Dockerfile.tde
    container_name: aeth-trading-defense
    ports:
      - "8999:8999"
    networks:
      - aeth-mesh
    restart: always

networks:
  aeth-mesh:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data:
